=== andrewathalye/kazakhbook/languages/shared/contexts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <!-- 
      Context scopes
   -->
   <xs:simpleType name="context_scope">
      <xs:restriction base="xs:string">
         <xs:enumeration value="phoneme"/>
         <xs:enumeration value="syllable"/>
         <xs:enumeration value="symbol"/>
         <xs:enumeration value="morpheme"/>
         <xs:enumeration value="word"/>
         <xs:enumeration value="clause"/>
         <xs:enumeration value="sentence"/>
         <xs:enumeration value="text"/>
      </xs:restriction>
   </xs:simpleType>
   <!-- 
      Definition of context
   -->
   <xs:group name="context_single">
      <xs:sequence>
         <xs:element name="anyprev" type="xs:string" minOccurs="0"/>
         <xs:element name="anynext" type="xs:string" minOccurs="0"/>
         <xs:element name="prev" type="xs:string" minOccurs="0"/>
         <xs:element name="next" type="xs:string" minOccurs="0"/>
         <xs:element name="unique" type="xs:string" minOccurs="0"/>
         <xs:element name="super" type="xs:string" minOccurs="0"/>
      </xs:sequence>
   </xs:group>
   <xs:complexType name="context_list">
      <xs:sequence>
         <xs:group ref="context_single" maxOccurs="unbounded"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="scoped_context">
      <xs:sequence>
         <xs:element name="not" type="context_list" minOccurs="0"/>
         <xs:element name="any" type="context_list" minOccurs="0"/>
         <xs:group ref="context_single"/>
      </xs:sequence>
      <xs:attribute name="level" type="context_scope" use="required"/>
      <xs:attribute name="within" type="context_scope" use="required"/>
   </xs:complexType>
   <xs:complexType name="context_def">
      <xs:sequence maxOccurs="unbounded">
         <xs:element name="scope" type="scoped_context"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:string" use="required"/>
   </xs:complexType>
   <!-- 
      Reference to context
   -->
   <xs:complexType name="context_ref">
      <xs:attribute name="ref" type="xs:string" use="required"/>
   </xs:complexType>
   <xs:element name="contexts">
      <xs:complexType>
         <xs:sequence maxOccurs="unbounded">
            <xs:element name="context" type="context_def"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
</xs:schema>

=== andrewathalye/kazakhbook/languages/kazakh/contexts.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
      Database of known contexts. Contexts are sets of feature-based
      conditions under which a form is to be chosen.
   -->
<contexts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../shared/contexts.xsd">
   <!--
      Phonology
   -->
   <!-- Between two vowels -->
   <context id="intervocalic">
      <scope level="phoneme" within="text">
         <prev>manner/vocalic</prev>
         <next>manner/vocalic</next>
      </scope>
   </context>
   <!-- Before a vowel, at the beginning of a word -->
   <context id="initial_prevocalic">
      <scope level="phoneme" within="word">
         <prev>[]</prev>
         <next>manner/vocalic</next>
      </scope>
   </context>
   <!-- Before a vowel -->
   <context id="prevocalic">
      <scope level="phoneme" within="word">
         <next>manner/vocalic</next>
      </scope>
   </context>
   <!-- Before a consonant -->
   <context id="preconsonantal">
      <scope level="phoneme" within="word">
         <not>
            <next>manner/vocalic</next>
         </not>
      </scope>
   </context>
   <context id="postconsonantal">
      <scope level="phoneme" within="word">
         <not>
            <prev>manner/vocalic</prev>
         </not>
      </scope>
   </context>
   <!-- After a vowel -->
   <context id="postvocalic">
      <scope level="phoneme" within="word">
         <prev>manner/vocalic</prev>
      </scope>
   </context>
   <!-- Stressed or initial -->
   <context id="initial_or_stressed">
      <scope level="phoneme" within="word">
         <any>
            <prev>[]</prev>
            <super>stressed</super>
         </any>
      </scope>
   </context>
   <!-- Stressed -->
   <context id="stressed">
      <scope level="phoneme" within="syllable">
         <super>stressed</super>
      </scope>
   </context>
   <!-- Initial -->
   <context id="initial">
      <scope level="phoneme" within="word">
         <prev>[]</prev>
      </scope>
   </context>
   <!-- Desinental -->
   <context id="desinental">
      <scope level="phoneme" within="word">
         <next>[]</next>
      </scope>
   </context>
   <!-- South Dialect -->
   <context id="south_dialect">
      <scope level="phoneme" within="text">
         <super>dialect/south</super>
      </scope>
   </context>
   <!-- West Dialect -->
   <context id="west_dialect">
      <scope level="phoneme" within="text">
         <super>dialect/west</super>
      </scope>
   </context>
   <!-- Following a syllable with ұ/ү -->
   <context id="post_closeclosemid_syllable">
      <scope level="phoneme" within="word">
         <anyprev>manner/vocalic height/closeclosemid</anyprev>
      </scope>
   </context>
   <!-- 
      Morphology
   -->
   <!-- 
         A word is countable iff it is a noun, personal pronoun
         or indefinite verb.
         There may only be one number marker in a word, number is not
         marked if there is a cardinal number preceding the word
         A case marker cannot come before a number marker.
      -->
   <context id="numbermarker">
      <scope level="morpheme" within="word">
         <not>
            <anyprev>case</anyprev>
            <super>uncountable</super>
         </not>
         <any>
            <super>word/noun</super>
            <super>word/pronoun</super>
            <super>word/verb mood/indefinite</super>
         </any>
         <unique>number</unique>
      </scope>
      <scope level="word" within="clause">
         <not>
            <anyprev>numberclass/cardinal</anyprev>
         </not>
      </scope>
   </context>
   <!-- 
         A case marker must only appear in a noun, declinable pronoun
         or indefinite verb.
         There may only be one case marker in a word.
      -->
   <context id="casemarker">
      <scope level="morpheme" within="word">
         <not>
            <super>indeclinable</super>
         </not>
         <any>
            <super>word/noun</super>
            <super>word/pronoun</super>
            <super>word/verb mood/indefinite</super>
         </any>
         <unique>case</unique>
      </scope>
   </context>
   <!-- 
         Possessive suffixes must not precede number markers or repeat
      -->
   <context id="possessive_suffix">
      <scope level="morpheme" within="word">
         <not>
            <anynext>number</anynext>
         </not>
         <unique>suffix/possessive</unique>
      </scope>
   </context>
   <!-- 
         Demonstrative suffixes do not repeat and occur only after
         a locative case ending.
      -->
   <context id="demonstrative_suffix">
      <scope level="morpheme" within="word">
         <prev>case/locative</prev>
         <unique>suffix/demonstrative</unique>
      </scope>
   </context>
   <!-- 
         Unique postfixes do not repeat
      -->
   <context id="unique_postfix">
      <scope level="morpheme" within="word">
         <unique>postfix/unique</unique>
      </scope>
   </context>
   <!-- 
         Only one interrogative particle may be in a clause
         and they must be at the end of the clause.
      -->
   <context id="interrogative_particle">
      <scope level="word" within="clause">
         <next>[]</next>
         <unique>particle/interrogative</unique>
      </scope>
   </context>
</contexts>
